# Generated by Django 5.2.3 on 2025-08-27 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
