# Generated by Django 5.2.3 on 2025-08-27 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.rentalitem')),
            ],
            options={
                'verbose_name': 'カレンダー状態',
                'verbose_name_plural': 'カレンダー状態',
                'unique_together': {('date', 'item')},
            },
        ),
    ]
