# Generated by Django 5.2.3 on 2025-08-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_calendarstatus'),
    ]

    operations = [
        # Drop the existing table and recreate it with proper structure
        migrations.RunSQL(
            "DROP TABLE IF EXISTS reservations_calendarstatus;",
            reverse_sql="CREATE TABLE IF NOT EXISTS \"reservations_calendarstatus\" (\"id\" integer NOT NULL PRIMARY KEY AUTOINCREMENT, \"date\" date NOT NULL UNIQUE, \"is_available\" bool NOT NULL);"
        ),
        migrations.CreateModel(
            name='CalendarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.rentalitem')),
            ],
            options={
                'verbose_name': 'カレンダー状態',
                'verbose_name_plural': 'カレンダー状態',
                'unique_together': {('date', 'item')},
            },
        ),
    ]
