# Generated by Django 5.2.3 on 2025-08-27 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20250827_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='キャンセル日時'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_number',
            field=models.CharField(default='KR000000000', editable=False, help_text='予約確認番号（自動生成）', max_length=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='noreply@example.com', help_text='予約確認メール送信用', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, help_text='特記事項があれば記入', verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='000-0000-0000', help_text='例: 090-1234-5678', max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号は10-15桁の数字とハイフンで入力してください', regex='^[0-9\\-]{10,15}$')], verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', '確定'), ('cancelled', 'キャンセル'), ('completed', '利用完了')], default='confirmed', max_length=20, verbose_name='予約ステータス'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='予約日時'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.rentalitem', verbose_name='レンタル物品'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='予約者名'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['confirmation_number'], name='reservation_confirm_71004a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'item'], name='reservation_date_eaf25e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
    ]
