# Generated by Django 5.2.3 on 2025-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_options_reservation_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_number',
            field=models.CharField(default='KR000000000', editable=False, help_text='予約確認番号（自動生成）', max_length=12, unique=True),
        ),
    ]
