# Generated by Django 5.2.3 on 2025-08-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_add_unique_confirmation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='total_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='総在庫数'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='warning_threshold',
            field=models.PositiveIntegerField(default=1, verbose_name='警告しきい値'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_number',
            field=models.CharField(blank=True, editable=False, help_text='予約確認番号（自動生成）', max_length=12, unique=True),
        ),
    ]
