# Generated by Django 5.2.3 on 2025-08-28 13:05

import django.db.models.deletion
import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_rentalitem_total_stock_rentalitem_warning_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='推奨サイズ: 800x600px, 最大ファイルサイズ: 5MB', upload_to=reservations.models.rental_item_image_path, verbose_name='画像')),
                ('alt_text', models.CharField(blank=True, help_text='画像の説明（アクセシビリティ向上）', max_length=200, verbose_name='代替テキスト')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順序')),
                ('is_primary', models.BooleanField(default=False, verbose_name='メイン画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservations.rentalitem', verbose_name='レンタル物品')),
            ],
            options={
                'verbose_name': 'レンタル物品画像',
                'verbose_name_plural': 'レンタル物品画像',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['item', 'order'], name='reservation_item_id_be89b8_idx'), models.Index(fields=['is_primary'], name='reservation_is_prim_18ea96_idx')],
            },
        ),
    ]
