# Generated by Django 5.2.3 on 2025-08-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_rentalitemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('adjusting', '調整中'), ('confirmed', '確定'), ('cancelled', 'キャンセル')], default='adjusting', max_length=20, verbose_name='予約ステータス'),
        ),
    ]
