# Generated by Django 5.2.3 on 2025-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('adjusting', '調整中'), ('completed', '予約完了'), ('cancelled', 'キャンセル')], default='adjusting', max_length=20, verbose_name='予約ステータス'),
        ),
    ]
