# Generated by Django 5.2.3 on 2025-08-29 21:57

from django.db import migrations

def update_confirmed_to_adjusting(apps, schema_editor):
    """既存の 'confirmed' ステータスを 'adjusting' に変更"""
    Reservation = apps.get_model('reservations', 'Reservation')
    Reservation.objects.filter(status='confirmed').update(status='adjusting')

def reverse_update(apps, schema_editor):
    """ロールバック時は 'adjusting' を 'confirmed' に戻す"""
    Reservation = apps.get_model('reservations', 'Reservation')
    Reservation.objects.filter(status='adjusting').update(status='confirmed')

class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_reservation_status'),
    ]

    operations = [
        migrations.RunPython(update_confirmed_to_adjusting, reverse_update),
    ]
