# Generated by Django 5.2.3 on 2025-08-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20250830_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(help_text='予約通知を受け取る管理者のメールアドレス', max_length=254, verbose_name='管理者メールアドレス')),
                ('send_customer_notification', models.BooleanField(default=True, help_text='予約者に確認メールを送信するかどうか', verbose_name='顧客への通知を送信')),
                ('send_admin_notification', models.BooleanField(default=True, help_text='管理者に予約通知メールを送信するかどうか', verbose_name='管理者への通知を送信')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'メール設定',
                'verbose_name_plural': 'メール設定',
            },
        ),
    ]
