# Generated by Django 5.2.3 on 2025-08-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_emailsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(help_text='管理者の名前（メール識別用）', max_length=100, verbose_name='名前')),
                ('is_active', models.BooleanField(default=True, help_text='このメールアドレスに通知を送信するかどうか', verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '管理者メールアドレス',
                'verbose_name_plural': '管理者メールアドレス',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='admin_email',
        ),
    ]
