# Generated by Django 5.2.3 on 2025-08-30 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_adminemail_remove_emailsettings_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemail',
            name='email_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_emails', to='reservations.emailsettings', verbose_name='メール設定'),
        ),
        migrations.AlterField(
            model_name='adminemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterUniqueTogether(
            name='adminemail',
            unique_together={('email_settings', 'email')},
        ),
    ]
