# Generated by Django 5.2.3 on 2025-08-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_adminemail_email_settings_alter_adminemail_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminemail',
            options={'ordering': ['name'], 'verbose_name': '通知先', 'verbose_name_plural': '通知先'},
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='from_email',
            field=models.EmailField(default='noreply@example.com', help_text='メールの送信者として使用するメールアドレス', max_length=254, verbose_name='送信者メールアドレス'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='from_name',
            field=models.CharField(default='予約システム', help_text='メールの送信者として表示される名前', max_length=100, verbose_name='送信者名'),
        ),
        migrations.AlterField(
            model_name='adminemail',
            name='name',
            field=models.CharField(help_text='通知先の名前（メール識別用）', max_length=100, verbose_name='名前'),
        ),
    ]
