# Generated by Django 5.2.3 on 2025-08-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_adminemail_options_emailsettings_from_email_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'item', 'status'], name='reservation_date_555fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['created_at', 'status'], name='reservation_created_8b1ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['phone', 'created_at'], name='reservation_phone_1f7007_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['email', 'created_at'], name='reservation_email_6a6265_idx'),
        ),
    ]
